// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "./javascript/components/data_ansices.jsx"
import "./javascript/components/data_level_type.jsx"
import "./javascript/components/data_parameters.jsx"
import "./javascript/components/data_popups_image.jsx"
import "./javascript/components/data_questions.jsx"
import "./javascript/components/data_tags.jsx"
import "./javascript/components/quiz_timer.jsx"
import "./javascript/controllers/paste_image.js"
import "./javascript/controllers/bootstrap.js"